// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBExmo74a57mTraZdHT1WyMdRVYPXS7oC8',
    appId: '1:411005340760:web:2a365153221afc56674e2d',
    messagingSenderId: '411005340760',
    projectId: 'bismi-16619',
    authDomain: 'bismi-16619.firebaseapp.com',
    storageBucket: 'bismi-16619.firebasestorage.app',
    measurementId: 'G-GGBBRFRB8B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDc__gpigWAwpbt_4Bj4-Ao13jPMTguk7A',
    appId: '1:411005340760:android:a7f38584e24b7cf9674e2d',
    messagingSenderId: '411005340760',
    projectId: 'bismi-16619',
    storageBucket: 'bismi-16619.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaMLn-mAsnSxGKBSSoysTk8K_hRNxPT3M',
    appId: '1:411005340760:ios:881ec718134127a2674e2d',
    messagingSenderId: '411005340760',
    projectId: 'bismi-16619',
    storageBucket: 'bismi-16619.firebasestorage.app',
    iosBundleId: 'com.example.bishmiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaMLn-mAsnSxGKBSSoysTk8K_hRNxPT3M',
    appId: '1:411005340760:ios:881ec718134127a2674e2d',
    messagingSenderId: '411005340760',
    projectId: 'bismi-16619',
    storageBucket: 'bismi-16619.firebasestorage.app',
    iosBundleId: 'com.example.bishmiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBExmo74a57mTraZdHT1WyMdRVYPXS7oC8',
    appId: '1:411005340760:web:a8b4b0655febf1e7674e2d',
    messagingSenderId: '411005340760',
    projectId: 'bismi-16619',
    authDomain: 'bismi-16619.firebaseapp.com',
    storageBucket: 'bismi-16619.firebasestorage.app',
    measurementId: 'G-NN71Q7381D',
  );
}
